/** Entry in public/preset-models.json — generated by scripts/seed-model-library.ts. */
export interface PresetModelEntry {
  id: string;
  name: string;
  gender: string;
  ethnicity: string;
  skinTone: string;
  bodyBuild: string;
  height: string;
  hairStyle: string;
  hairColor: string;
  ageRange: string;
  imageUrl: string;
  generatedAt: string;
  /** Reserved for future tier gating — not yet enforced. */
  tier?: 'free' | 'paid';
}

export interface ModelAttributes {
  name: string;
  gender: string;
  ethnicity: string;
  skinTone: string;
  bodyBuild: string;
  height: string;
  hairStyle: string;
  hairColor: string;
  ageRange: string;
}

/** Canonical model gender values. Use for snippet resolution; keep in sync with model builder / preset data. */
export const MODEL_GENDER = ['Female', 'Male', 'Non-binary'] as const;
export type ModelGender = (typeof MODEL_GENDER)[number];

/** Returns the value if it's a known model gender, else undefined (treat as default snippet). */
export function normalizeModelGender(value: string | undefined): ModelGender | undefined {
  if (value == null) return undefined;
  return MODEL_GENDER.includes(value as ModelGender) ? (value as ModelGender) : undefined;
}

export interface StylingDirectionPreset {
  id: string;
  label: string;
  /** Optional image path for brand-style UI (e.g. /presets/styling/minimal.png). */
  imageUrl?: string;
  description?: string;
  /** Injected into the front pose prompt — replaces the hardcoded neutral pose sentence. */
  frontSnippet: string;
  /** Short energy cue appended to 3/4 and back prompts — kept terse to avoid confusing multi-turn chat context. */
  energyCue: string;
  /** When modelGender is 'Male', use this for front pose if present; else use frontSnippet. */
  frontSnippetMale?: string;
  /** When modelGender is 'Male', use this for 3/4 and back if present; else use energyCue. */
  energyCueMale?: string;
  /** Full three-quarter pose instruction. When present, replaces the generic "45° body turn" line. */
  threeQuarterSnippet?: string;
  /** When modelGender is 'Male', use this for 3/4 pose if present; else use threeQuarterSnippet. */
  threeQuarterSnippetMale?: string;
  /** Backdrop/background prompt snippet — drives the studio background for this direction. */
  backdropSnippet: string;
}

export interface PdpStylePreset {
  id: string;
  label: string;
  /** Optional image path for brand-style UI (e.g. /presets/backgrounds/white-studio.png). */
  imageUrl?: string;
  /** Optional short description for workspace UI (e.g. White / Grey studio). */
  description?: string;
  promptSnippet: string;
}

export interface AnglePreset {
  id: string;
  label: string;
  /** Optional image path for brand-style UI (e.g. /presets/poses/front.png). */
  imageUrl?: string;
  promptSnippet: string;
}

export interface GeneratedImage {
  id: string;
  url: string;
  attributes: ModelAttributes;
  timestamp: number;
  prompt: string;
  styleId?: string;
  angleId?: string;
  /** Same for all images in one generation (multi-angle run). Used to group gallery cards. */
  batchId?: string;
  /** 'flat_lay' = dressed from flat lay upload; undefined = model-only generation. */
  sourceType?: 'model_only' | 'flat_lay';
  /** Optional SKU label (for flat-lay runs); display/badges and future batch. */
  skuName?: string;
  /** Links this image back to its BatchOutfitItem.id so it can be re-generated individually. */
  outfitQueueId?: string;
}

export interface BatchOutfitItem {
  id: string;
  frontFile: File;
  frontThumbUrl: string;
  frontFilename: string;
  backFile: File | null;
  backThumbUrl: string | null;
  skuName: string;
  /** Per-outfit style override; defaults to selectedStyleIds[0] at creation time. */
  styleId?: string;
  /** Cached garment spec from Phase 1 extraction; used for single-pose regen. */
  garmentSpec?: import('./garmentSpec').GarmentSpec;
  status: 'pending' | 'extracting' | 'generating' | 'done' | 'error';
  currentPose: number;
  errorMessage: string | null;
}

export interface BatchProgress {
  currentOutfit: number;
  totalOutfits: number;
  currentPose: number;
  totalPoses: number;
  label: string;
  phase: 'extracting' | 'generating';
}

export type ViewMode = 'builder' | 'gallery' | 'outfit-gallery' | 'model-picker';
