/** Entry in public/preset-models.json — generated by scripts/seed-model-library.ts. */
export interface PresetModelEntry {
  id: string;
  name: string;
  gender: string;
  ethnicity: string;
  skinTone: string;
  bodyBuild: string;
  height: string;
  hairStyle: string;
  hairColor: string;
  ageRange: string;
  imageUrl: string;
  generatedAt: string;
  /** Reserved for future tier gating — not yet enforced. */
  tier?: 'free' | 'paid';
}

export interface ModelAttributes {
  name: string;
  gender: string;
  ethnicity: string;
  skinTone: string;
  bodyBuild: string;
  height: string;
  hairStyle: string;
  hairColor: string;
  ageRange: string;
}

export interface StylingDirectionPreset {
  id: string;
  label: string;
  description?: string;
  /** Injected into the front pose prompt — replaces the hardcoded neutral pose sentence. */
  frontSnippet: string;
  /** Short energy cue appended to 3/4 and back prompts — kept terse to avoid confusing multi-turn chat context. */
  energyCue: string;
}

export interface PdpStylePreset {
  id: string;
  label: string;
  /** Optional short description for workspace UI (e.g. White / Grey studio). */
  description?: string;
  promptSnippet: string;
}

export interface AnglePreset {
  id: string;
  label: string;
  promptSnippet: string;
}

export interface GeneratedImage {
  id: string;
  url: string;
  attributes: ModelAttributes;
  timestamp: number;
  prompt: string;
  styleId?: string;
  angleId?: string;
  /** Same for all images in one generation (multi-angle run). Used to group gallery cards. */
  batchId?: string;
  /** 'flat_lay' = dressed from flat lay upload; undefined = model-only generation. */
  sourceType?: 'model_only' | 'flat_lay';
  /** Optional SKU label (for flat-lay runs); display/badges and future batch. */
  skuName?: string;
  /** Links this image back to its BatchOutfitItem.id so it can be re-generated individually. */
  outfitQueueId?: string;
}

export interface BatchOutfitItem {
  id: string;
  frontFile: File;
  frontThumbUrl: string;
  frontFilename: string;
  backFile: File | null;
  backThumbUrl: string | null;
  skuName: string;
  /** Per-outfit style override; defaults to selectedStyleIds[0] at creation time. */
  styleId?: string;
  /** Cached garment spec from Phase 1 extraction; used for single-pose regen. */
  garmentSpec?: import('./garmentSpec').GarmentSpec;
  status: 'pending' | 'extracting' | 'generating' | 'done' | 'error';
  currentPose: number;
  errorMessage: string | null;
}

export interface BatchProgress {
  currentOutfit: number;
  totalOutfits: number;
  currentPose: number;
  totalPoses: number;
  label: string;
  phase: 'extracting' | 'generating';
}

export type ViewMode = 'builder' | 'gallery' | 'outfit-gallery' | 'model-picker';
