/**
 * OpenAPI 3.1 discovery document served at /openapi.json.
 *
 * Three consumers read it with slightly different expectations:
 *   - `mppx validate` / MPPScan: `x-payment-info` per operation with
 *     `method`, `intent`, `amount`, `currency`, `offers` (generated by mppx).
 *   - AgentCash: `x-payment-info.price` + `protocols`, `info.x-guidance`,
 *     `responses.402`, a JSON `requestBody` schema.
 *   - x402scan / Bazaar: the same operation plus the runtime PAYMENT-REQUIRED.
 * All three schemas are open, so one merged object satisfies each.
 */
import { generate as generateMppDiscovery, type DiscoveryHandler } from "mppx/discovery";
import { getSupportEmail } from "../support.server";
import {
  ON_MODEL_DESCRIPTION,
  ON_MODEL_JOBS_PATH,
  ON_MODEL_PATH,
  ON_MODEL_PRICE_USD,
  ON_MODEL_SUMMARY,
  publicOrigin,
  realmFor,
} from "./config.server";
import { getMppx, getOnModelCharge, mppStatus } from "./mpp.server";
import {
  ON_MODEL_EXAMPLE_INPUT,
  ON_MODEL_EXAMPLE_OUTPUT,
  ON_MODEL_EXAMPLE_PROCESSING,
  onModelInputSchema,
  onModelOutputSchema,
} from "./onModelJob.server";
import { x402Status } from "./x402.server";

const GUIDANCE =
  "Tiny Lemon turns a garment flat-lay into an on-model studio photo. " +
  `POST ${ON_MODEL_PATH} with {garmentImageUrl} (https PNG/JPEG/WebP) or {garmentImageBase64}, ` +
  "optionally modelId (see the enum) and wait (seconds). The call costs $0.50 and is payable with " +
  "MPP (Authorization: Payment) or x402 (PAYMENT-SIGNATURE). Generation takes 45-90 seconds: if the " +
  "response is 202, GET the returned statusUrl every 5 seconds for free until status is completed, " +
  "then download image.url. Do not pay again for the same job. 400 responses are free and mean the " +
  "input was rejected before payment.";

type OperationObject = Record<string, unknown>;

export async function buildOpenApiDocument(request: Request): Promise<Record<string, unknown>> {
  const origin = publicOrigin(request);
  const realm = realmFor(request);
  const mpp = mppStatus();
  const x402 = x402Status();

  const requestBody = {
    required: true,
    content: {
      "application/json": {
        schema: onModelInputSchema(),
        example: ON_MODEL_EXAMPLE_INPUT,
      },
    },
  };

  let doc: Record<string, unknown> | null = null;
  const mppx = mpp.enabled ? await getMppx(realm) : null;
  const charge = mppx ? await getOnModelCharge(realm) : null;
  if (mppx && charge) {
    doc = generateMppDiscovery(
      { methods: mppx.methods as Parameters<typeof generateMppDiscovery>[0]["methods"], realm: mppx.realm },
      {
        info: { title: "Tiny Lemon on-model API", version: "1.0.0" },
        routes: [
          {
            handler: charge as unknown as DiscoveryHandler,
            method: "POST",
            path: ON_MODEL_PATH,
            requestBody,
            summary: ON_MODEL_SUMMARY,
          },
        ],
        serviceInfo: {
          categories: ["images", "fashion", "ecommerce", "generation"],
          docs: { homepage: "https://tinylemon.xyz", apiReference: `${origin}/openapi.json` },
        },
      },
    );
  }

  doc ??= {
    openapi: "3.1.0",
    info: { title: "Tiny Lemon on-model API", version: "1.0.0" },
    paths: { [ON_MODEL_PATH]: { post: {} } },
  };

  const info = (doc.info ??= {}) as Record<string, unknown>;
  info.description = ON_MODEL_DESCRIPTION;
  info["x-guidance"] = GUIDANCE;
  info.contact = { name: "Tiny Lemon", email: getSupportEmail(), url: "https://tinylemon.xyz" };
  doc.servers = [{ url: origin }];

  const paths = (doc.paths ??= {}) as Record<string, Record<string, OperationObject>>;
  const post = (paths[ON_MODEL_PATH] ??= {}).post ?? {};
  const existingPaymentInfo = (post["x-payment-info"] ?? {}) as Record<string, unknown>;

  const protocols: Array<Record<string, unknown>> = [];
  if (x402.enabled) protocols.push({ x402: {} });
  if (mpp.enabled) {
    const offers = (existingPaymentInfo.offers ?? []) as Array<Record<string, unknown>>;
    if (offers.length > 0) {
      for (const offer of offers) {
        protocols.push({
          mpp: { method: offer.method ?? "", intent: offer.intent ?? "charge", currency: offer.currency ?? "" },
        });
      }
    } else {
      protocols.push({
        mpp: {
          method: existingPaymentInfo.method ?? "tempo",
          intent: existingPaymentInfo.intent ?? "charge",
          currency: existingPaymentInfo.currency ?? "",
        },
      });
    }
  }

  paths[ON_MODEL_PATH].post = {
    ...post,
    operationId: "generateOnModelImage",
    summary: ON_MODEL_SUMMARY,
    description: ON_MODEL_DESCRIPTION,
    tags: ["on-model"],
    requestBody,
    responses: {
      "200": {
        description: "Image ready.",
        content: { "application/json": { schema: onModelOutputSchema(), example: ON_MODEL_EXAMPLE_OUTPUT } },
      },
      "202": {
        description: "Paid and queued; poll statusUrl (free) until completed.",
        content: {
          "application/json": { schema: onModelOutputSchema(), example: ON_MODEL_EXAMPLE_PROCESSING },
        },
      },
      "400": { description: "Invalid input. No payment was taken." },
      "402": { description: "Payment Required (MPP WWW-Authenticate: Payment and/or x402 PAYMENT-REQUIRED)." },
      "413": { description: "Garment image larger than 10 MB. No payment was taken." },
      "502": { description: "Generation failed after payment; contact support with jobId." },
    },
    "x-payment-info": {
      ...existingPaymentInfo,
      // mppx forbids flat fields (amount/currency/description/intent/method)
      // next to `offers`; every offer already carries its own description.
      ...(Array.isArray(existingPaymentInfo.offers) ? {} : { description: ON_MODEL_SUMMARY }),
      price: { mode: "fixed", currency: "USD", amount: ON_MODEL_PRICE_USD },
      protocols,
      ...(x402.enabled
        ? {
            x402: {
              network: x402.network,
              payTo: x402.payTo,
              scheme: "exact",
              facilitator: x402.facilitator,
            },
          }
        : {}),
    },
  };

  paths[`${ON_MODEL_JOBS_PATH}/{jobId}`] = {
    get: {
      operationId: "getOnModelJob",
      summary: "Poll a generation job (free)",
      description: "Returns the same object as the paid call. No payment required.",
      tags: ["on-model"],
      // An explicit empty security array is how AgentCash infers "unprotected".
      security: [],
      parameters: [
        {
          name: "jobId",
          in: "path",
          required: true,
          schema: { type: "string" },
          example: ON_MODEL_EXAMPLE_OUTPUT.jobId,
        },
      ],
      responses: {
        "200": {
          description: "Job state.",
          content: { "application/json": { schema: onModelOutputSchema(), example: ON_MODEL_EXAMPLE_OUTPUT } },
        },
        "404": { description: "Unknown jobId." },
      },
    },
  };

  paths[ON_MODEL_PATH].get = {
    operationId: "describeOnModel",
    summary: "Describe the endpoint and list preset models (free)",
    tags: ["on-model"],
    security: [],
    responses: { "200": { description: "Price, protocols, and preset models." } },
  };

  return doc;
}
